micronaut:
  application:
    name: labb2micronaut

  mongodb.uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/formula1"
#mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
 # mongodb://user:password@${MONGO_HOST:driver}:${MONGO_PORT:27017}/formula1
netty:
  default:
    allocator:
      max-order: 3
formula1:
  name: 'driver'
  collection: 'driver'