name: FormulaOne
on:
  release:
    types: [ published ]
  push:
    branches: [ $default-branch ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ $default-branch ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.com/GreenGard/labb2micronautformelOne.git }}


jobs:
  compile-and-test:
    runs-on: ubuntu-latest


steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: 17'
      distribution: temurin
      cache: maven


build-and-publish-executable-and-image:
    needs: [ compile-and-test ]
    runs-on: ubuntu-latest
permissions:
contents: read
packages: write

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
              java-version: 17'
              distribution: temurin'
              cache: maven

          - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


        - name: Run test
          run: mvnw test

        - name: Build and push Docker image
          id: build-and-push
          run: mvnw package -Dpackaging=docker-native -Pgraalvm

        - name: Sign the published Docker image
          run: |
            docker tag labb2micronautformelOne:latest ${{ env.IMAGE_NAME }}:latest
            docker push ${{ env.IMAGE_NAME }}:latest
            docker tag labb2micronautformelOne:latest ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
