
name: Build Java CI with Maven
on:
  release:
    types: [ created ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Allow access to mvnw
        run: chmod +x mvnw

      - name: Build a docker image
        run: ./mvnw package -Dpackaging=docker-native -Pgraalvm

      - name: Push Docker image
        run: |
          docker tag labb2micronautformelone:latest ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
          docker tag llabb2micronautformelone:latest ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
